### PR TITLE
ADR-0039 Consistent typing of real numbers

### PR DESCRIPTION
**Pull request by schuur**
ADR for uniform typing of real numbers, proposal for v3. Backwards incompatible changes.

### CODE REVIEW

**Review by bhadley — APPROVED** [review]
LGTM!

**Comment by scottgifford** [comment]
Agree with standardization, but wondering about the type names.  I notice the naming here is inconsistent with [JSON schema](https://json-schema.org/understanding-json-schema/reference) type naming, which uses `integer` for integers and `number` for real numbers.  It looks like we are proposing `Number` for the integer type (which I didn't see defined in the [current spec](https://wbcsd.github.io/data-exchange-protocol/v2/)), and `Decimal` changing from its meaning in the current spec to a new type which is a real number expressed as a string, because it allows clients more control over the precision of that number.  Are those names consistent with another standard?  If not, they seem confusing to me, vs. e.g. `Integer` and `DecimalString`.

**Review by mill6-plat6aux — APPROVED** [review]
Thank you for putting together the ADR. I have no problem with the content.
It is important that Tech Specs have a consistent policy regarding data types.
I think there will be no confusion if the next major version of Tech Spec clearly defines how the Decimal type is implemented.

**Comment by schuur** [comment]
@scottgifford: totally agree with your observations on type names. 

The tech specs refer to the JavaScript types, like **String**, **Boolean** but also **Number** https://tc39.es/ecma262/#sec-numbers-and-dates (and no Integer). However, in JSON Schema (and by extension OpenAPI 3.1+) there is a distinct **integer** (and **string**, **boolean**) type. 

Starting v3 it makes sense in the technical specification to refer to the OpenAPI schema types (string, integer, boolean - all lowercase, denoting standard stuff) and use Decimal or DecimalString for the string formatted real numbers. The Pascal casing already indicates the use of a custom type.

**Comment by FlorianAJ** [comment]
I received some feedback from the AEAG which implemented the data model from Catena-X in IMDS. Their feedback is also relevant for pact in this context. They requested a specification of how many digits should be communicated for percentages (for percentages only! e.g.Primary data share).

**Comment by schuur** [comment]
@FlorianAJ: the precision for the real numbers (including the percentages) is something which can vary for different contexts. One of the reasons for settling on a string-formatted Decimal is that it allows for unlimited precision, not being implicitly bound by implementations for floating-point numbers in the programming languages which parse the JSON data. It is therefore up to the data owner to decide what precision makes sense given a certain context.

**Comment by schuur** [comment]
Given the consensus discussed in the working groups, and the comments on this PR (thank you!) will be merging the request.
@scottgifford the consistent naming of the other types (integer, boolean) will be part of a separate PR targeted for v3

**Pull request merged**
