### PR TITLE
docs(spec v2): clarify unit of `fossilCarbonContent` and `biogenicCarbonContent`

### PR DESCRIPTION
**Pull request by zeitgeist**
see changelog for details of this PR

### CODE REVIEW

**Comment by JorritZuidema** [comment]
@zeitgeist - hi Martin, Can we remove the space between kg and C (see line 212 and 450)?

For example, fossilGhgEmissions is using the unit kgCO2e. It would be great if CarbonContent is consistent and uses the unit kgC.

**Review by JorritZuidema — CHANGES_REQUESTED** [review]
I suggest changing the unit of measure to; kgC (without space between kg and C). This is consistent with the unit of measure for kgCO2e (without space between kg and CO2e).

**Comment by zeitgeist** [comment]
Dear @JorritZuidema , thank you for your review. Should have addressed your comment with 7813f1189ae41333c10c0a8f0b8b5114289f809a. Please review again.

**Review by JorritZuidema — APPROVED** [review]
Perfect thank you!

**Review by raimundo-henriques — APPROVED** [review]

**Pull request merged**
